### ISSUE TITLE
error decompressing FCIDUMP file

### ISSUE THREAD

**Issue by jp7745** [isi-usc-edu/qb-gsee-benchmark#71]
Please inspect the relevant FCIDUMP file to ensure it's still good.  If not, update file on the SFTP server, and also update the checksum for the file in the associated `problem_instance`.

`sftp://sftp.l3harris.com/gsee/small_molecules/fcidump.c_h3_cl_cc-pVTZ.a53ae008-4ad2-4736-9a57-cfc011e3aace.gz`
(fixed that SFTP URL... in the original ticket I had the wrong URL)

when running the Hamiltonian features calculation script, decompressing the following Hamiltonian FCIDUMP throws an error:

bash```
2024-12-11 07:58:41,358 - INFO - decompressing file fcidump.c_h3_cl_cc-pVTZ.a53ae008-4ad2-4736-9a57-cfc011e3aace.gz...
Traceback (most recent call last):
  File "/home/labuser/Projects/qb-gsee-benchmark/scripts/./compute_all_ham_features_script.py", line 495, in <module>
    main(args)
  File "/home/labuser/Projects/qb-gsee-benchmark/scripts/./compute_all_ham_features_script.py", line 332, in main
    shutil.copyfileobj(f_in, f_out)
  File "/usr/lib/python3.10/shutil.py", line 195, in copyfileobj
    buf = fsrc_read(length)
  File "/usr/lib/python3.10/gzip.py", line 301, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.10/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.10/gzip.py", line 507, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

another attempt from the command line:

bash```
gunzip fcidump.c_h3_cl_cc-pVTZ.a53ae008-4ad2-4736-9a57-cfc011e3aace.gz

gzip: fcidump.c_h3_cl_cc-pVTZ.a53ae008-4ad2-4736-9a57-cfc011e3aace.gz: unexpected end of file
```

**Comment by jp7745** [comment]
@jtcantin :  any progress on this?  This is the last Hamiltonian outstanding for the "features" calculation.

**Comment by jtcantin** [comment]
@jp7745 Sorry for the delay
When I download via winSCP, I can open the file with 7-zip. The fcidump file also appears normal in vim (it is too large to open with VS code or notepad).

The same happens when I try decompressing in Ubuntu (WSL2) with `gunzip`.

I've noticed that this file is the largest of the fcidumps on the sftp server: ~400 MB vs the next largest of ~350MB

Given that it is an EOF error, could the script have attempted `gunzip` before the file was fully downloaded?
